/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManualFillRouteImport } from './routes/manual-fill'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as AdminGeofenceRouteImport } from './routes/admin.geofence'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminBulkRouteImport } from './routes/admin.bulk'

const ManualFillRoute = ManualFillRouteImport.update({
  id: '/manual-fill',
  path: '/manual-fill',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeofenceRoute = AdminGeofenceRouteImport.update({
  id: '/geofence',
  path: '/geofence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkRoute = AdminBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/manual-fill': typeof ManualFillRoute
  '/admin/bulk': typeof AdminBulkRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/geofence': typeof AdminGeofenceRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/manual-fill': typeof ManualFillRoute
  '/admin/bulk': typeof AdminBulkRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/geofence': typeof AdminGeofenceRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/manual-fill': typeof ManualFillRoute
  '/admin/bulk': typeof AdminBulkRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/geofence': typeof AdminGeofenceRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/manual-fill'
    | '/admin/bulk'
    | '/admin/drivers'
    | '/admin/geofence'
    | '/admin/trips'
    | '/admin/vehicles'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manual-fill'
    | '/admin/bulk'
    | '/admin/drivers'
    | '/admin/geofence'
    | '/admin/trips'
    | '/admin/vehicles'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/manual-fill'
    | '/admin/bulk'
    | '/admin/drivers'
    | '/admin/geofence'
    | '/admin/trips'
    | '/admin/vehicles'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ManualFillRoute: typeof ManualFillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manual-fill': {
      id: '/manual-fill'
      path: '/manual-fill'
      fullPath: '/manual-fill'
      preLoaderRoute: typeof ManualFillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/geofence': {
      id: '/admin/geofence'
      path: '/geofence'
      fullPath: '/admin/geofence'
      preLoaderRoute: typeof AdminGeofenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk': {
      id: '/admin/bulk'
      path: '/bulk'
      fullPath: '/admin/bulk'
      preLoaderRoute: typeof AdminBulkRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBulkRoute: typeof AdminBulkRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminGeofenceRoute: typeof AdminGeofenceRoute
  AdminTripsRoute: typeof AdminTripsRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBulkRoute: AdminBulkRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminGeofenceRoute: AdminGeofenceRoute,
  AdminTripsRoute: AdminTripsRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ManualFillRoute: ManualFillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
